version: "3.8"

# volumes:
  

services:
  ginx:
    tty: true
    build:
      context: .
    container_name: ginx
    env_file:
      - .env.docker
    volumes:
      - .:/var/www:cached
    ports:
      - 80:80
      - 443:443
